import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
// Data
import data from "../data/bitcoins.json";
// Images
import bitcoin from "@public/img/Bitcoin.svg";
import checkCircleIcon from "@public/icons/check-circle.svg";
import eyeIcon from "@public/icons/eye.svg";
import dollarIcon from "@public/icons/dollar-sign.svg";
import clockIcon from "@public/icons/clock.svg";
import batataIcon from "@public/icons/batata.svg";
import bitcoinbaby from "@public/img/bitcoinbaby.jpg";
// Components
import {
  Rates,
  SlideItem,
  Benefits,
  BenefitsBody,
  BenefitsItem,
  BenefitsIcon,
  BenefitsHeader,
  WildCard,
  Plans,
  PlanCard,
  PlanCards,
} from "@components/index";
// Styles
import { Container } from "@styles/components/container";
import { colors } from "@styles/variables/colors";
import { Title, Text } from "@styles/shared";
import { Slide } from "@styles/components/slide";
import { useState } from "react";

const Home: NextPage = () => {
  const [indexActive, setIndexActive] = useState(0);
  const [indexCardActive, setIndexCardActive] = useState(0);

  const nextSlide = (index: number) => {
    if (index < sliderItems.length - 1) {
      setIndexActive(index + 1);
    } else {
      setIndexActive(0);
    }
  };

  const nextCard = (index: number) => {
    if (index < sliderCard.length - 1) {
      setIndexCardActive(index + 1);
    } else {
      setIndexCardActive(0);
    }
  };

  const backCard = (index: number) => {
    if (index > 0) {
      setIndexCardActive(index - 1);
    } else {
      setIndexCardActive(sliderCard.length - 1);
    }
  };

  const sliderItems = [
    {
      item: (index: number) => (
        <SlideItem
          key={index}
          index={index}
          indexActive={indexActive}
          title="Monedas"
          titleColor={colors.bitcoinOrange}
          messageColor={colors.softOrange}
          nextSlide={nextSlide}
          data={data.bitcoins}
        />
      ),
    },
    {
      item: (index: number) => (
        <SlideItem
          key={index}
          index={index}
          indexActive={indexActive}
          title="Comisiones"
          titleColor={colors.secundaryBlue}
          messageColor={colors.softBlue}
          nextSlide={nextSlide}
          data={data.commissions}
        />
      ),
    },
  ];

  const sliderCard = [
    {
      card: (index: number) => (
        <PlanCard
          key={index}
          title="Pago anual"
          textValue="99"
          text="*Ahorras $129 comparado al plan mensual"
          floatText
          headerText="Recomendado"
          index={index}
          indexCardActive={indexCardActive}
          btnText="Escoge este"
          nextCard={nextCard}
          backCard={backCard}
        />
      ),
    },
    {
      card: (index: number) => (
        <PlanCard
          key={index}
          title="Pago mensual"
          textValue="19"
          text="*Pagas $129 comparado al plan anual"
          index={index}
          indexCardActive={indexCardActive}
          btnText="Escoge este"
          nextCard={nextCard}
          backCard={backCard}
        />
      ),
    },
    {
      card: (index: number) => (
        <PlanCard
          key={index}
          title="Pago semanal"
          textValue="5"
          text="*Pagas $1 más comparado al plan mensual"
          index={index}
          indexCardActive={indexCardActive}
          btnText="Escoge este"
          nextCard={nextCard}
          backCard={backCard}
        />
      ),
    },
  ];

  return (
    <div>
      <Head>
        <title>Crypto App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Rates>
          <Image src={bitcoin} alt="bitcoin" />
          <Title size="2rem" align="center">
            Visibilizamos todas las tasas de cambio
          </Title>
          <Text size="1.3rem" align="center" color={colors.grey}>
            Traemos información en tiempo real de las casas de cambio y las
            monedas más importantes del mundo.
          </Text>
          <Slide>{sliderItems.map((item, index) => item.item(index))}</Slide>
        </Rates>
        <Benefits>
          <BenefitsIcon icon={batataIcon} />
          <BenefitsHeader>
            <Title size="2rem" align="center" color="white">
              Creamos un producto sin comparación.
            </Title>
            <Text size="1.3rem" align="center" color={colors.grey}>
              Confiable y diseñado para su uso diario.
            </Text>
          </BenefitsHeader>
          <BenefitsBody>
            <BenefitsItem
              icon={clockIcon}
              title="Tiempo real"
              text={`Nuestro API toma información minuto a minuto sobre las tasas que más determinan
              el comportamiento.`}
            />
            <BenefitsItem
              icon={eyeIcon}
              title="No hay tasa escondidad"
              text={`Ni en la compra o al momento de exit, Batabit siempre te muestr el costo real de
              lo que estás adquiriendo.`}
            />
            <BenefitsItem
              icon={dollarIcon}
              title="Compara monedas"
              text={`No más reumores, con Babtabit sabrás el valor real de cada moneda en el mercado
              actual.`}
            />
            <BenefitsItem
              icon={checkCircleIcon}
              title="Información confiable"
              text={`Nuestras fuentes están 100% verificadas y continuamos asuditando su contenido
              mientras se actualizan.`}
            />
          </BenefitsBody>
        </Benefits>
        <WildCard>
          <Image
            src={bitcoinbaby}
            layout="fill"
            alt="bitcoinbaby"
            quality="100"
            objectFit="cover"
          ></Image>
          <Title size="2.5rem" color={colors.white} floating align="center">
            <strong>Conócelo hoy.</strong>
          </Title>
        </WildCard>
        <Plans id="plans">
          <Title size="2rem" align="center">
            Escoge el plan que mejor se ajuste a ti
          </Title>
          <Text size="1.3rem" align="center" color={colors.grey}>
            Cualquier plan te da acceso completo a nuestra plataforma.
          </Text>
          <PlanCards>
            {sliderCard.map((card, index) => card.card(index))}
          </PlanCards>
        </Plans>
      </Container>
    </div>
  );
};

export default Home;
